### ISSUE TITLE
No Release File

### ISSUE THREAD

**Issue by passionventures** [deimosfr/ansible-mariadb#8]
Hi @deimosfr,

The role is throwing following error message:

""changed": false, "msg": "E:The repository 'http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/debian bionic Release' does not have a Release file."}"

Does it work on of the box or do you need to provide an extra variable with repo?

**Comment by deimosfr** [comment]
Hi,

It works out of the box. I didn't used it since a long time now. I may have
to change the url. If you have a working one, feel free to make a pull
request.

Thanks

Le mar. 8 mai 2018 à 15:57, passionventures <notifications@github.com> a
écrit :

**Comment by rsanzante** [comment]
The repo url changed. I've fixed with this commit:

https://github.com/rsanzante/ansible-mariadb/commit/14878aa0149b220addb84a675fe0662e4bfa8f3c
